# Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_play"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_play"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Run on start
on-run-start:
    - "{{ create_udfs() }}"

# Variables
vars:
    start_date: "2021-01-01"
    execution_date: "notset"
    dataset_udf: "_utils"

# Model config
models:
  dbt_play:
    marts:
      materialized: table
      +dataset: marts
      +tags:
        - "marts"
        - "daily"

    intermediate:
      +materialized: incremental
      +dataset: intermediate
      +tags:
        - "intermediate"
        - "daily"

    staging:
      materialized: view
      +dataset: staging
      +tags:
        - "staging"
        - "daily"

    python:
      +materialized: table
      +dataset: python_models  # This can be irrelevant for local runs
      +tags:
        - "python"
        - "ml"
      customer_segmentation:
        +enabled: false
        +profile: "{{ 'local_python' if target.name == 'local_python' else 'dev' }}"  # Switch to local profile for Python models
      revenue_forecast:
        +enabled: false
        +profile: "{{ 'local_python' if target.name == 'local_python' else 'dev' }}"  # Switch to local profile for Python models
      product_recommendations:
        +enabled: false
        +profile: "{{ 'local_python' if target.name == 'local_python' else 'dev' }}"  # Switch to local profile for Python models
            