dbt_play:
  target: dev  # Default target can be set to dev or prod
  outputs:
    dev:
      type: bigquery
      method: oauth  # Other methods include service-account, oauth-secrets, etc.
      project: dbt-playground-421906
      dataset: dev_ecommerce  # Development dataset
      threads: 4
      timeout_seconds: 300
      location: EU  # Specify the location if needed
      priority: interactive

    prod:
      type: bigquery
      method: oauth
      project: dbt-playground-421906
      dataset: prod_ecommerce  # Production dataset
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
